Dev
ViniciusSilva3/ES pull request #4
Opened 2022-03-12 00:26 UTC by ViniciusSilva3

Add Create user endpoint at POST /api/user.

The request body has following format:
```
{
    "cpf": "123456788",
    "password": "1234567",
    "cardNumber": "1234567890",
    "cardDate": "2020/01/02",
    "cardDigits": "555"
}
```

2022-03-16 13:20 UTC, zerbinidamata requested changes
LGTM! Some files are missing an empty line at the end, some tools can't find the EOF without that empty line

2022-03-16 13:20 UTC, zerbinidamata commented on v2.0/ES/Constants/DatabaseConstants.cs
> +}
Missing line in the end of the file

2022-03-16 13:20 UTC, zerbinidamata commented on v2.0/ES/Db/Persister.cs
> +}
Same here

2022-03-16 13:20 UTC, zerbinidamata commented on v2.0/ES/Services/UserService.cs
> +}
Same

2022-03-16 13:29 UTC, felipebayres commented
👍

2022-03-18 02:28 UTC, zerbinidamata approved these changes

2022-03-20 21:39 UTC, merged

2022-03-21 00:48 UTC, zerbinidamata commented
👍